add jamver

diff --git a/cxn b/cxn
--- a/cxn
+++ b/cxn
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 # VARS #
-version=1.2
-modified="11/April/2021"
+version=1.3
+modified="03/August/2021"
 
 # NULL INPUT CAPTURE #
 if [[ -z $1 ]]; then
@@ -57,6 +57,27 @@ if [[ $1 == 'jam' ]]; then
   if [[ $2 =~ ^[c|m|u][0-9]{1,2}$ ]]; then
     echo "valid server $2 - attempting connection."
     ssh -i /auth/keys/$key root@$2.jam.maguscloud.com
+  else
+    echo "invalid server detected: $2"
+  fi
+  exit 1;
+fi
+
+# JAMVER #
+if [[ $1 == 'jamver' ]]; then
+  echo "JAMver ssh syntax detected."
+  key='key-ast-general.pem'
+  if [[ -z $2 ]]; then
+    echo "No server parameters entered"
+    exit 1;
+  fi
+  if [[ $2 == 'key' ]]; then
+    echo "Using key: $key"
+    exit 1;
+  fi
+  if [[ $2 =~ ^[c|m|u][0-5]$ ]]; then
+    echo "valid server $2 - attempting connection."
+    ssh -i /auth/keys/$key ubuntu@$2.ver.dqm.cprd.io
   else
     echo "invalid server detected: $2"
   fi
