Add listing and range feature sets to jb script

diff --git a/jb b/jb
--- a/jb
+++ b/jb
@@ -1,7 +1,7 @@
 #!/bin/bash
 # VARS #
-version=1.0.2
-modified="9 August 2020"
+version=1.1.0
+modified="4 November 2020"
 
 mboxes=38 # Can edit the number of M boxes here
 pkey="/auth/keys/master-vpc-keypair-us-east-1.pem" # Replace local pem key here
@@ -22,10 +22,41 @@ if [ $1 == 'version' ]; then
    exit 1;
 fi
 
+# JBOSS RANGE
+if [[ $1 == 'range' ]]; then
+  echo "Current range set to $mboxes"
+  echo "Change manually, and commit permanent range increases to the repository."
+  exit 1;
+fi
+
 # JBOSS LOOP LIST #
-if [ $1 == 'list' ]; then
-	i="0"
-	echo "Listing jboss backend service state"
+if [[ $1 == 'list' ]]; then
+	i=0
+  if [[ -z $2 ]]; then
+    i=0
+  fi
+  if [[ $2 -ge $i ]]; then
+    i=$[$2-1]
+  fi
+  # to
+  if [[ -z $3 ]]; then
+    echo "Running to end"
+  fi
+  if [[ $3 -ge $mboxes ]]; then
+    echo "invalid selection"
+  fi
+  if [[ $3 -le $2 ]]; then
+    echo "from is greater than to.."
+  fi
+  if [[ $3 -gt $2 ]] && [[ $3 -le $mboxes ]]; then
+    echo "Lowering endpoint value"
+    mboxes=$3
+  fi
+  if [[ $i -lt 0 ]]; then
+    i=0
+  fi
+  # Main loop
+	echo "Listing jboss backend service state from $[$i+1] to $mboxes"
   while [ $i -lt $mboxes ]
 	do
 		i=$[$i+1]
@@ -101,6 +132,25 @@ if [ $1 == 'restart' ]; then
     done
 fi
 
+# JBOSS SSH RESET
+if [[ $1 == 'reset' ]] && [[ $2 == 'keys' ]]; then
+  echo "Resetting all ssh keys"
+  cd ~/.ssh
+  dir=`pwd`
+  cd -
+  i=0
+  while [ $i -lt $mboxes ]
+    do
+      i=$[$i+1]
+      echo ""
+      echo "============"
+      echo "Checking m$i"
+      echo "============"
+      ssh-keygen -f "$dir/known_hosts" -R "m$i.jam.maguscloud.com"
+    done
+  exit 1;
+fi
+
 # JBOSS HELP
 if [ $1 == 'help' ]; then
 	clear
@@ -117,5 +167,6 @@ if [ $1 == 'help' ]; then
 	echo "jb script  - displays script execution details"
 	echo "jb         - any other value ignored."
 fi
+
 
 exit;
