copy down copy up feature for jb tool

diff --git a/jb b/jb
--- a/jb
+++ b/jb
@@ -1,7 +1,7 @@
 #!/bin/bash
 # VARS #
-version=2.2.1
-modified="09 July 2021"
+version=2.3.1
+modified="11 October 2021"
 
 mboxes=30 # Can edit the number of M boxes here
 pkey="/auth/keys/master-vpc-keypair-us-east-1.pem" # Replace local pem key here
@@ -450,6 +450,37 @@ if [[ $1 == 'logs' ]]; then
   exit 1;
 fi
 
+# JBOSS COPY-DOWN COPY-UP
+if [[ $1 == 'copy' ]]; then
+  echo "Syntax is jb copy-down|copy-up [server]"
+  echo "This will copy all *.*ar files to or from your local workstation from your current location"
+  exit 1;
+fi
+if [[ $1 == 'copy-down' ]]; then
+  if [[ -z $2 ]]; then
+    echo "Please also enter a valid servername, e.g. m4"
+    exit 1;
+  fi
+  if [[ $2 =~ ^[c|m][0-9]{1,2}$ ]]; then
+    echo "valid server $2 - copying files."
+    scp -i $pkey root@$2.jam.maguscloud.com:/jboss/standalone/deployments/*.*ar .
+  else
+    echo "invalid server detected: $2"
+  fi
+fi
+if [[ $1 == 'copy-up' ]]; then
+  if [[ -z $2 ]]; then
+    echo "Please also enter a valid servername, e.g. m4"
+    exit 1;
+  fi
+  if [[ $2 =~ ^[c|m][0-9]{1,2}$ ]]; then
+    echo "valid server $2 - copying files to server."
+    scp -i $pkey *.*ar root@$2.jam.maguscloud.com:/jboss/standalone/deployments/
+  else
+    echo "invalid server detected: $2"
+  fi
+fi
+
 # TEST BLOCK
 if [[ $1 == 'test' ]]; then
   echo "This is a test loop"
@@ -471,20 +502,22 @@ if [[ $1 == 'help' ]]; then
 	echo "============================"
 	echo ""
 	echo "Options are:"
-	echo "jb help    - Displays this help page."
-  echo "jb version - Displays the version of the current script that you have installed."
-  echo "jb stop    - Stop jboss on all M servers, but not M1"
-	echo "jb start   - Start jboss on all M servers, but not M1"
-  echo "jb restart - Stops and restarts all jboss services from M2 to the end."
-	echo "jb list    - List all deployed versions for selected range. Defaults is to display all servers"
-  echo "           - options to list harvest, trawl or monitor services (server list for each service)"
-	echo "jb logs    - Outputs selected logs for a jboss server to a local logs directory"
-  echo "           - jb logs [server] [apache|spelling|jboss etc]"
-	echo "jb range   - Displays the parameter range that has been set"
-  echo "jb report  - Outputs .csv report to file"
-	echo "jb script  - Displays script execution details"
-  echo "jb uptime  - Displays the uptime since last server start-up"
-	echo "jb         - any other value ignored."
+	echo "jb help      - Displays this help page."
+  	echo "jb version   - Displays the version of the current script that you have installed."
+  	echo "jb stop      - Stop jboss on all M servers, but not M1"
+	echo "jb start     - Start jboss on all M servers, but not M1"
+  	echo "jb restart   - Stops and restarts all jboss services from M2 to the end."
+	echo "jb list      - List all deployed versions for selected range. Defaults is to display all servers"
+  	echo "             - options to list harvest, trawl or monitor services (server list for each service)"
+	echo "jb logs      - Outputs selected logs for a jboss server to a local logs directory"
+  	echo "             - jb logs [server] [apache|spelling|jboss etc]"
+	echo "jb range     - Displays the parameter range that has been set"
+  	echo "jb report    - Outputs .csv report to file"
+	echo "jb script    - Displays script execution details"
+  	echo "jb uptime    - Displays the uptime since last server start-up"
+	echo "jb copy-down - Copies all jboss artifacts from the remote server to your current working directory"
+	echo "jb copy-up   - Copies all jboss artifacts from your current working directory to the remote server"
+	echo "jb           - any other value ignored."
 fi
 
 exit;
