Added restart functionality for monitor and trawl, plus list capability for t, h and m

diff --git a/jb b/jb
--- a/jb
+++ b/jb
@@ -1,7 +1,7 @@
 #!/bin/bash
 # VARS #
-version=1.1.0
-modified="4 November 2020"
+version=1.1.2
+modified="28 December 2020"
 
 mboxes=38 # Can edit the number of M boxes here
 pkey="/auth/keys/master-vpc-keypair-us-east-1.pem" # Replace local pem key here
@@ -9,7 +9,7 @@ pkey="/auth/keys/master-vpc-keypair-us-east-1.pem" # Replace local pem key here
 # NULL INPUT CAPTURE #
 if [ -z $1 ]; then
    echo "Missing option - nothing to execute"
-   echo "Usage: jb (start|stop|restart|list|version|help)"
+   echo "Usage: jb (range|start|stop|restart|list|version|help)"
    exit 1;
 fi
 
@@ -32,6 +32,73 @@ fi
 # JBOSS LOOP LIST #
 if [[ $1 == 'list' ]]; then
 	i=0
+  if [[ $2 == 'monitor' ]]; then
+    # Monitor specific commands
+    >monitor.txt
+    i="1"
+     echo "Looking for monitor services..."
+     while [ $i -lt $mboxes ]
+     do
+       i=$[$i+1]
+       echo "m$i" >> monitor.txt
+       ssh -o StrictHostKeyChecking=no -i $pkey root@m$i.jam.maguscloud.com 'ls -la /jboss/standalone/deployments/*monitor*.ear 2> /dev/null' >>monitor.txt
+     done
+     # Tidy up file
+     echo "m40" >> monitor.txt
+     echo `cat monitor.txt` > monitor.txt
+     cp monitor.txt monitor-results.txt
+     for i in {1..5}; do sed -i -r 's/m[0-9]{1,2}\sm/m/g' monitor.txt; done
+     sed -i 's/\([0-9]\)\s/\1\n/g' ./monitor.txt
+     sed -i 's/\/jboss.*ear\s//g' ./monitor.txt
+     cat monitor.txt | grep m | grep -v m40 > monitors.txt
+     cat monitors.txt
+     rm -f ./monitor*.txt
+     exit 1;
+  fi
+  if [[ $2 == 'trawl' ]]; then
+    # Trawl specific commands
+    >trawl.txt
+    i="1"
+     echo "Looking for trawl services..."
+     while [ $i -lt $mboxes ]
+     do
+       i=$[$i+1]
+       echo "m$i" >> trawl.txt
+       ssh -o StrictHostKeyChecking=no -i $pkey root@m$i.jam.maguscloud.com 'ls -la /jboss/standalone/deployments/*trawl*.ear 2> /dev/null' >>trawl.txt
+     done
+     # Tidy up file
+     echo "m40" >> trawl.txt
+     echo `cat trawl.txt` > trawl.txt
+     for i in {1..5}; do sed -i -r 's/m[0-9]{1,2}\sm/m/g' trawl.txt; done
+     sed -i 's/\([0-9]\)\s/\1\n/g' ./trawl.txt
+     sed -i 's/\/jboss.*ear\s//g' ./trawl.txt
+     cat trawl.txt | grep m | grep -v m40 > trawlers.txt
+     cat trawlers.txt
+     rm -f ./trawl*.txt
+     exit 1;
+  fi
+  if [[ $2 == 'harvest' ]]; then
+    # Harvest specific commands
+    >harvest.txt
+    i="1"
+     echo "Looking for harvest services..."
+     while [ $i -lt $mboxes ]
+     do
+       i=$[$i+1]
+       echo "m$i" >> harvest.txt
+       ssh -o StrictHostKeyChecking=no -i $pkey root@m$i.jam.maguscloud.com 'ls -la /jboss/standalone/deployments/*harvest*.ear 2> /dev/null' >>harvest.txt
+     done
+     # Tidy up file
+     echo "m40" >> harvest.txt
+     echo `cat harvest.txt` > harvest.txt
+     for i in {1..5}; do sed -i -r 's/m[0-9]{1,2}\sm/m/g' harvest.txt; done
+     sed -i 's/\([0-9]\)\s/\1\n/g' ./harvest.txt
+     sed -i 's/\/jboss.*ear\s//g' ./harvest.txt
+     cat harvest.txt | grep m | grep -v m40 > harvesters.txt
+     cat harvesters.txt
+     rm -f ./harvest*.txt
+     exit 1;
+  fi
   if [[ -z $2 ]]; then
     i=0
   fi
@@ -119,17 +186,77 @@ fi
 
 # JBOSS RESTART
 if [ $1 == 'restart' ]; then
-  i="1"
-    echo "Restarting jboss on all backend servers (not M1)"
-    while [ $i -lt $mboxes ]
-    do
-      i=$[$i+1]
-      echo ""
-      echo "============"
-      echo "Starting m$i"
-      echo "============"
-      ssh -o StrictHostKeyChecking=no -i $pkey root@m$i.jam.maguscloud.com 'service jboss stop && service jboss start'
-    done
+  if [ -z $2 ]; then
+       i="1"
+       echo "Restarting jboss on all backend servers (not M1)"
+       while [ $i -lt $mboxes ]
+       do
+         i=$[$i+1]
+         echo ""
+         echo "============"
+         echo "Starting m$i"
+         echo "============"
+         ssh -o StrictHostKeyChecking=no -i $pkey root@$i.jam.maguscloud.com 'service jboss stop'
+         ssh -o StrictHostKeyChecking=no -i $pkey root@$i.jam.maguscloud.com 'service jboss start'
+       done
+       exit 1;
+  fi
+  if [ $2 == 'monitor' ]; then
+    echo "Restarting all MONITOR boxes"
+    >monitor.txt
+    i="1"
+     echo "Looking for monitor services..."
+     while [ $i -lt $mboxes ]
+     do
+       i=$[$i+1]
+       echo "m$i" >> monitor.txt
+       ssh -o StrictHostKeyChecking=no -i $pkey root@m$i.jam.maguscloud.com 'ls -la /jboss/standalone/deployments/*monitor*.ear 2> /dev/null' >>monitor.txt
+     done
+     # Tidy up file
+     echo "m40" >> monitor.txt
+     echo `cat monitor.txt` > monitor.txt
+     cp monitor.txt monitor-results.txt
+     for i in {1..5}; do sed -i -r 's/m[0-9]{1,2}\sm/m/g' monitor.txt; done
+     sed -i 's/\([0-9]\)\s/\1\n/g' ./monitor.txt
+     sed -i 's/\/jboss.*ear\s//g' ./monitor.txt
+     cat monitor.txt | grep m | grep -v m40 > monitors.txt
+     lines=$(cat monitors.txt)
+     for i in $lines; do
+       ssh -o StrictHostKeyChecking=no -i $pkey root@$i.jam.maguscloud.com 'service jboss stop'
+       ssh -o StrictHostKeyChecking=no -i $pkey root@$i.jam.maguscloud.com 'service jboss start'
+       echo "Restarted jboss on $i"
+     done
+     rm monitor*.txt
+     exit 1;
+  fi
+  if [ $2 == 'trawl' ]; then
+    echo "Restarting all TRAWL boxes"
+    >monitor.txt
+    i="1"
+     echo "Looking for trawl services..."
+     while [ $i -lt $mboxes ]
+     do
+       i=$[$i+1]
+       echo "m$i" >> trawl.txt
+       ssh -o StrictHostKeyChecking=no -i $pkey root@m$i.jam.maguscloud.com 'ls -la /jboss/standalone/deployments/*trawl*.ear 2> /dev/null' >>trawl.txt
+     done
+     # Tidy up file
+     echo "m40" >> trawl.txt
+     echo `cat trawl.txt` > trawl.txt
+     for i in {1..5}; do sed -i -r 's/m[0-9]{1,2}\sm/m/g' trawl.txt; done
+     sed -i 's/\([0-9]\)\s/\1\n/g' ./trawl.txt
+     sed -i 's/\/jboss.*ear\s//g' ./trawl.txt
+     cat trawl.txt | grep m | grep -v m40 > trawlers.txt
+     lines=$(cat trawlers.txt)
+     for i in $lines; do
+       ssh -o StrictHostKeyChecking=no -i $pkey root@$i.jam.maguscloud.com 'service jboss stop'
+       ssh -o StrictHostKeyChecking=no -i $pkey root@$i.jam.maguscloud.com 'service jboss start'
+       echo "Restarted jboss on $i"
+     done
+     rm trawl*.txt
+     exit 1;
+  fi
+  echo "Invalid option $2"
 fi
 
 # JBOSS SSH RESET
@@ -151,6 +278,28 @@ if [[ $1 == 'reset' ]] && [[ $2 == 'keys' ]]; then
   exit 1;
 fi
 
+# JBOSS UPTIME
+if [[ $1 == 'uptime' ]]; then
+  i="0"
+	 echo "Checking uptime of all jboss server instances"
+   while [ $i -lt $mboxes ]
+   do
+     i=$[$i+1]
+     echo ""
+     echo "============"
+     echo "Checking m$i"
+     echo "============"
+     ssh -o StrictHostKeyChecking=no -i $pkey root@m$i.jam.maguscloud.com 'w | grep up' | awk {'print $3" "$4" "$5'}
+   done
+   for i in {1..5}; do
+      echo ""
+      echo "==========="
+      echo "Checking c$i"
+      echo "==========="
+      ssh -o StrictHostKeyChecking=no -i $pkey root@m$i.jam.maguscloud.com 'w | grep up' | awk {'print $3" "$4" "$5'}
+    done
+fi
+
 # JBOSS HELP
 if [ $1 == 'help' ]; then
 	clear
@@ -158,13 +307,16 @@ if [ $1 == 'help' ]; then
 	echo "============================"
 	echo ""
 	echo "Options are:"
-	echo "jb stop    - to stop jboss on all M servers, but not M1"
-	echo "jb start   - to start jboss on all M servers, but not M1"
-	echo "jb list    - to list all deployed versions in the standard deployments directory, for all servers"
-	echo "jb restart - stops and restarts all jboss services from M2 to the end."
-	echo "jb version - displays the version of the current script that you have installed."
-	echo "jb help    - displays this help page."
-	echo "jb script  - displays script execution details"
+	echo "jb stop    - Stop jboss on all M servers, but not M1"
+	echo "jb start   - Start jboss on all M servers, but not M1"
+	echo "jb list    - List all deployed versions for selected range. Defaults is to display all servers"
+  echo "           - options to list harvest, trawl or monitor services (server list for each service)"
+	echo "jb restart - Stops and restarts all jboss services from M2 to the end."
+	echo "jb version - Displays the version of the current script that you have installed."
+	echo "jb help    - Displays this help page."
+	echo "jb script  - Displays script execution details"
+  echo "jb range   - Displays the parameter range that has bee set"
+  echo "jb uptime  - Displays the uptime since last server start-up"
 	echo "jb         - any other value ignored."
 fi
 
